"""
Example VEYN Consumer Agent
Demonstrates connecting to the VEYN daemon and streaming real-time cognitive context.
"""

import json
import os
import sys
import time
import httpx

TOKEN_PATH = "/data/veyn/token"
VEYN_BASE = "http://veyn:7700"

def main():
    print("=== VEYN Consumer Agent ===")
    
    # Wait for token file to be generated by daemon
    for _ in range(30):
        if os.path.exists(TOKEN_PATH):
            break
        print("Waiting for VEYN daemon token...", flush=True)
        time.sleep(1.0)
        
    if not os.path.exists(TOKEN_PATH):
        print(f"Error: Token file not found at {TOKEN_PATH}", file=sys.stderr)
        sys.exit(1)
        
    with open(TOKEN_PATH, "r") as f:
        token = f.read().strip()
        
    headers = {"Authorization": f"Bearer {token}"}
    
    # Check daemon health
    try:
        resp = httpx.get(f"{VEYN_BASE}/health", headers=headers, timeout=10.0)
        health = resp.json()
        print(f"✓ Connected to VEYN daemon (v{health.get('version')})")
        print(f"✓ Uptime: {health.get('uptime_s')}s")
    except Exception as e:
        print(f"Error connecting to daemon: {e}", file=sys.stderr)
        sys.exit(1)
        
    print("\nStreaming real-time cognitive context (Ctrl+C to stop)...", flush=True)
    params = {"token": token, "min_confidence": "0.5"}
    
    with httpx.Client(timeout=None) as client:
        with client.stream("GET", f"{VEYN_BASE}/v1/context/subscribe", params=params) as stream:
            for line in stream.iter_lines():
                if line.startswith("data:"):
                    try:
                        snap = json.loads(line[5:])
                        ts = snap.get("timestamp_ms", 0)
                        intent = snap.get("intent", "unknown")
                        conf = snap.get("confidence", 0.0)
                        print(f"[{ts}] {intent} ({conf:.2f})", flush=True)
                    except json.JSONDecodeError:
                        pass

if __name__ == "__main__":
    main()
